services:
  postgres:
    container_name: eveent-pg
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: eveent
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres